name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-2022]
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      run: |
        cd pla_live_map_lib
        cargo build --release
        echo ${{ github.workspace }}
    - uses: actions/upload-artifact@v2
      with:
        name: pla_live_map_lib-${{ matrix.os }}
        path: |
          ${{ github.workspace }}/pla_live_map_lib/target/release/pla_live_map_lib.*
          ${{ github.workspace }}/pla_live_map_lib/target/release/pla_live_map_lib
